### ISSUE TITLE
Template output problem

### ISSUE THREAD

**Issue by Bie-NHD** [ianprime0509/eleventy-plugin-static-jsx#27]
Greetings, I'm currently experiencing unexpected behaviors as follow:

- My template, ```first.jsx``` at ```_includes\layouts\first.jsx```
```
import { RawHtml } from "static-jsx";

export default function render({ content: children, title, today }) {
	return (
		<>
			{/* JSX doesn't support doctypes natively, so we have to use RawHtml */}
			{new RawHtml("<!DOCTYPE html>")}
			<html lang="en">
				<head>
					<meta charset="utf-8" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<title>Eleventy | {title}</title>
				</head>
				<body>
					<main>
						<h2>heya</h2>
						<h1>{children}</h1>
					</main>				
				</body>
			</html>
		</>
	);
}
```
- My content ```content\testjsx.md``` (both .md and .mdx files experiencing the same behaviour)
```
---
layout: "layouts/first.jsx"
title: "Test with JSX"
---

Test with JSX

# This is the heading

```
- The output at ```_site\testjsx\index.html```
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Eleventy | Test with JSX</title>
	</head>
	<body>
		<main>
			<h2>heya</h2>
			<h1>
				&lt;p&gt;Test with JSX&lt;/p&gt; &lt;h1&gt;This is the
				heading&lt;/h1&gt;
			</h1>
		</main>
	</body>
</html>

```
- Screenshot:
![Screenshot for visual demonstration of the issue](https://github.com/ianprime0509/eleventy-plugin-static-jsx/assets/102498861/06e3162e-4bf5-48a3-b340-5f82d084bb3b)

Thank you so much for making this plugin happen! My best regards!

**Comment by ianprime0509** [comment]
Thanks for reaching out and giving this project a try!

In `first.jsx`, can you try this change?

```diff
-export default function render({ content: children, title, today }) {
+export default function render({ children, title, today }) {
```

`content` is the raw property used by Eleventy to pass child content to the layout, and `children` is created by the plugin by wrapping `content` in `RawHtml`: https://github.com/ianprime0509/eleventy-plugin-static-jsx/blob/62eb808fc90d0648bf66777c4aa0810db685bf85/index.js#L15-L18

If you try to use `content` directly, without wrapping it in `RawHtml`, it will be escaped, as you're seeing in your output above; `children` is used as a shortcut for this so you don't have to worry about `RawHtml` every time.

If this works for you, I'll add a note to the README making this more explicit.

**Comment by Bie-NHD** [comment]
Thank you so much! The problem is resolved with the change in ```{ content: children, }``` to ```{ children }```

**Comment by ianprime0509** [comment]
Thanks for confirming! I added an additional note to the README to make this distinction more explicit.
